config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'

  get 'shopping_list' => 'shopping_list/index'

  # don't need both of these. Test
  get '/recipes/:id' => 'recipes#add'
  post '/recipes/:id' => 'recipes#add'

  resources :recipes, :plans, :shopping_lists
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :amounts
  has_many :recipes, through: :amounts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :plans
  has_many :amounts
  has_many :ingredients, through: :amounts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :plans

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    if user = User.find_by(:email => auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
        user = User.new
        user.provider = auth.provider
        user.uid      = auth.uid
        user.name     = auth.info.name
        user.email     = auth.info.email
        user.password = "password"
        user.password_confirmation = "password"
        user.save
        user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # helper for Google+ login
  before_filter do
    resource = controller_path.singularize.gsub('/', '_').to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  # old logins, don't delete yet

  # private

  # def current_user
  #   User.find_by(id: session[:user_id])
  # end
  # helper_method :current_user

  # def logged_in?
  #   !!current_user
  #   # if current_user.present?
  #   #   true
  #   # else
  #   #   false
  #   # end
  # end
  # helper_method :logged_in?

  # def authenticate
  #   redirect_to login_path unless logged_in?

  #   # @current_user = User.find_by(:id => session[:user_id])
  #   # session[:user_id] = nil unless @current_user.present?

  #   # if @current_user.present?
  #   # else
  #   #   session[:user_id] = nil
  #   # end
  # end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # Google+ login helper
  def google_oauth2
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in Through Google!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "You are almost Done! Please provide a password to finish setting up your account"
      redirect_to new_user_registration_url
    end
  end

  # private
  def google_params
    params.require(:note).permit(:what, :ever)
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @plans = Plan.where(user_id: current_user.id)
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    redirect_to '/'
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    case params[:meal_type]
      when "breakfast"
        @recipes = Recipe.where(meal_type: "Breakfast")
      when "lunch"
        @recipes = Recipe.where(meal_type: "Lunch")
      when "dinner"
        @recipes = Recipe.where(meal_type: "Dinner")
      else
        @recipes = Recipe.all
    end
  end

  # method to add the recipe to the users meal plan
  def add
    if user_signed_in?
      recipe = Recipe.find(params[:id])
      plan = Plan.create(user_id: current_user.id, recipe_id: recipe.id)

      redirect_to '/'
    else
      redirect_to '/users/sign_in'
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate!

  def new
  end

  def create

    user = User.where(:name => params[:username]).first

    if user.present? && user.authenticate(params[:password])
      # correct password
      session[:user_id] = user.id
      redirect_to root_path
    else
      # incorrect password
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @ingredients = current_user.plans.joins(:recipe => :ingredients)

    sql = "select sum(a.grams), i.name from plans p join recipes r on (p.recipe_id=r.id) join amounts a on (a.recipe_id=r.id) join ingredients i on (a.ingredient_id=i.id) where p.user_id = #{current_user.id} group by i.name, a.ingredient_id order by a.ingredient_id;"
    @plans = ActiveRecord::Base.connection.execute(sql)
  end

  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user.create(name: params[:username], password: params[:password], email: params[:email])

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to login_path
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comidas: Meal & Shopping List Planner</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="../assets/style.css">
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= yield %>

    <div id="main-container" class="container">
      <div class="row">
        <div id="content" class="col-xs-12">
          <div class="row">
              <% if user_signed_in? %>
              <footer>
                <p class="footer">&copy; Comidas Food Planner
                <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'footer'  %>
                <%= link_to 'Home', "/", class: "footer"  %>
                </p>
              </footer>
              <% end %>
          </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-2.1.3.min.js" type="text/javascript"></script>
</body>
</html>

app/views/plans/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12">
      <a href="/">
        <img class ="logo-black" src="http://i.imgur.com/6RfQASd.png?1" alt="">
      </a>

      <h1>Your Meal Plans: </h1>

      <% total_calories = 0 %>
      <% total_meals = 0 %>

      <% @plans.each do |plan| %>
        <h3><%= plan.recipe.name %></h3>
        <% i = plan.recipe.instructions.split("//") %>
        <% n = 1 %>

        <% i.each do |instruction| %>
          <p><%= "#{n}) #{instruction }" %></p>
          <% n += 1 %>
        <% end %>
        <p><%= link_to 'DELETE', plan, :method => :delete  %></p>
        <p>Calories: <%= plan.recipe.calories %></p>
        <% total_calories += plan.recipe.calories %>
        <% total_meals += 1 %>
      <% end %>

      <h3>Total Calories: <%= total_calories %></h3>

      <h4>Over <%= total_meals %> Meals</h4>

      <% if total_meals == 0 %>
          <%= link_to 'Add Recipes', root_path, class: "btn btn-outline-dark" %>
      <% else %>
          <h2>Average Calories Per Meal: <%= total_calories / total_meals %></h2>
          <%= link_to 'Add More Recipes', root_path, class: "btn btn-outline-dark" %>
      <% end %>

      <%= link_to 'View Shopping List', shopping_lists_path, class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<header>
  <section class="hero" id="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center inner">
          <h1 class="white logo">Comidas</h1>
          <h4 class="white planner">Diet Planner</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <% if user_signed_in? %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: "btn btn-outline" %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</header>
   <div id="main-container" class="container">
      <div class="row">
        <div id="content" class="col-xs-12">
          <div class="row">
          <div class="col-md-12 text-left">
            <h1>Recipes</h1>
            <% if user_signed_in? %>
              <p><%= link_to 'Your Current Plans', plans_path %></p>
            <% end %>

            <%= link_to 'all', '/recipes/?meal_type=all', class: "btn btn-default" %>
            <%= link_to 'breakfast', '/recipes/?meal_type=breakfast', class: "btn btn-default" %>
            <%= link_to 'lunch', '/recipes/?meal_type=lunch', class: "btn btn-default" %>
            <%= link_to 'dinner', '/recipes/?meal_type=dinner', class: "btn btn-default" %>
          </div>
          <% @recipes.each do |recipe| %>
            <div id="content" class="col-md-4">
              <h2 class="food"><%= recipe.name %></h2>
                <img src="<%= recipe.image_url %>" alt="">
                <p class="calories">Calories: <%= recipe.calories %></p>
                <p><a href="/recipes/<%= recipe.id %>" recipe_id="<%= recipe.id %>" class="add">ADD</a></p>
            </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/shopping_lists/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="content" class="col-xs-12">
      <h1>Shopping List: </h1>
      <p>(grams/ml)</p>
      <hr>

      <% @plans.each do |ingredient|%>
        <p><%= ingredient['name'] %>  <%= ingredient['sum'] %></p>
      <% end %>
    </div>
  </div>
</div>